### ISSUE TITLE
Limitations of num_coordinate_component_dofs

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/ffcx#157]
Currently there are several limitations in the `num_coordinate_component_dofs`, https://github.com/FEniCS/ffcx/blob/master/ffc/codegeneration/definitions.py#L16-L44.

-  Does not support higher order quadrilaterals (Fix in PR #156, this fix should work for arbitrary order quadrilateral elements).
-  Does not support any mesh with degree > 3.

Until recently, there was no support in dolfin for meshes with higher order than 2. Now that we have added order 3 triangles, extending this to arbitrary order is tempting.
Then, as the comment in `num_coordinate_components_dofs` we should get this info from FIAT through IR.

**Comment by jorgensd** [comment]
Suggested fix for this issue is to replace the current loop with:
```
    from ffc.fiatinterface import create_element
    fiat_element = create_element(coordinate_element).elements()[0]
    dof_dict = fiat_element.entity_dofs()
    e = 0
    for key in dof_dict.keys():
        for key2 in dof_dict[key]:
            e = max(dof_dict[key][key2]) if (len(dof_dict[key][key2])>0 and max(dof_dict[key][key2]) > e) else e
    e += 1
    print(d, e)
    assert(d == e)
```
There might be a prettier way of doing this

**Comment by jorgensd** [comment]
Prettier version:
```
  from ffc.fiatinterface import create_element
    fiat_element = create_element(coordinate_element).elements()[0]
    dof_dict = fiat_element.entity_dofs()
    e = 0
    for key in dof_dict.keys():
        for key2 in dof_dict[key]:
            e+= len(dof_dict[key][key2])
```
This snippets generates a fiat element for the coordinate element, obtains its entity dofs and loops over them adding up the number of dofs for each entity.

**Comment by garth-wells** [comment]
Functionality has been moved to Basix.
