### ISSUE TITLE
Make kernels thread-safe

### ISSUE THREAD

**Issue by michalhabera** [FEniCS/ffcx#202]
Because C kernels with local static arrays, kernels are no longer thread-safe. This creates issues especially with numba's `parallel=True` attempts.

We should consider trading threaded performance for non-threaded with static arrays.

The reason behind violation of thread-safety should be investigated more, as we have `const static` arrays.

**Comment by mrambausek** [comment]
Did you experience any issues here? AFAIK, as long as the static data is "const", everything is safe but I might be wrong.

**Comment by michalhabera** [comment]
Yes, you are right, `const` should fix that here. But I had issues when using numba's parallel option on custom kernels. I will upload MWE soon and look into this.

**Comment by michalhabera** [comment]
So `static` is probably safe here, however, I am getting wrong results for SC demo https://github.com/FEniCS/dolfinx/blob/master/python/demo/mixed-elasticity-sc/static-condensation-elasticity.py 

Here is part of Numba's parallel diagnostics, 
```
Parallel loop listing for  Function tabulate_condensed_tensor_A, test_threads.py (115) 
--------------------------------------------------------------------------------------------------|loop #ID
@numba.cfunc(c_signature, nopython=True, parallel=True)                                           | 
def tabulate_condensed_tensor_A(A_, w_, c_, coords_, entity_local_index, cell_orientation):       | 
    # Prepare target condensed local elem tensor                                                  | 
    A = numba.carray(A_, (Usize, Usize), dtype=PETSc.ScalarType)                                  | 
                                                                                                  | 
    # Tabulate all sub blocks locally                                                             | 
    A00 = numpy.zeros((Ssize, Ssize), dtype=PETSc.ScalarType)-------------------------------------| #1
    kernel00(ffi.from_buffer(A00), w_, c_, coords_, entity_local_index, cell_orientation)         | 
                                                                                                  | 
    A01 = numpy.zeros((Ssize, Usize), dtype=PETSc.ScalarType)-------------------------------------| #2
    kernel01(ffi.from_buffer(A01), w_, c_, coords_, entity_local_index, cell_orientation)         | 
                                                                                                  | 
    A10 = numpy.zeros((Usize, Ssize), dtype=PETSc.ScalarType)-------------------------------------| #3
    kernel10(ffi.from_buffer(A10), w_, c_, coords_, entity_local_index, cell_orientation)         | 
                                                                                                  | 
    # A = - A10 * A00^{-1} * A01                                                                  | 
    A[:, :] = - A10 @ numpy.linalg.solve(A00, A01)------------------------------------------------| #4, 0
```

I have also tried version with just trivial wrapping of one local kernel and that works OK. I think now that calls to different compiled local kernels is problematic.

**Comment by mrambausek** [comment]
Weird... does numba recognize that the last line (#4, 0) has to be done after all other operations were completed? (I do not have any experience with parallel numba, but I am curious)

**Comment by garth-wells** [comment]
Static tables are const, so kernels look thread safe to me.
