### ISSUE TITLE
Turn on strict compiler options for tests

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/ffcx#211]
Add ` -Wall -pedantic -Werror` to pick up code problems early. 

See #207.

**Comment by mscroggs** [comment]
Many compiler warnings are now removed by #214, but I'm getting one (unused variable) that appears to be caused by the following:
https://github.com/FEniCS/ffcx/blob/0473e328a9ca21da849d53e9127c1547046c3bff/ffcx/codegeneration/evaluatedof.py#L327

**Comment by michalhabera** [comment]
Solved via #216 and #214 . `-pedantic` is not included but doesn't seems to be an easy fix.
