### ISSUE TITLE
Provide rank (in tensor sense) of an expression in generated code

### ISSUE THREAD

**Issue by mrambausek** [FEniCS/ffcx#257]
Currently, ffcx generates a "value_shape" attribute as a fixed size array for compiled expressions. However, there is no information about the length of this array which makes the interface incomplete. 
Note that from python one can access the value_shape array beyond its actual bounds without any problems (just getting a zero). I suppose cffi does some magic here to treat this properly.
As a second point, for scalars (rank zero) ffcx currently generates 
```
static const int value_shape[0] = { 0 };
```
which gives a compiler warning.

**Comment by mrambausek** [comment]
Did not see that there is num_components which does the job. The second point of the comiler warning then is a different story.

**Comment by mrambausek** [comment]
Sorry for spamming on this

**Comment by michalhabera** [comment]
Can you create a short and simple PR which would just avoid compiler warning for scalar values expressions?

**Comment by mrambausek** [comment]
Yes, working on it. What do you think about the name of num_components? I find it confusing since my first interpretation would some kind of size of the actual data array but not of the shape array.
