### ISSUE TITLE
Remove `alignas` option, set sensible default `assume_aligned`.

### ISSUE THREAD

**Issue by jhale** [FEniCS/ffcx#282]
`alignas` concerns the alignment of data structures allocated inside the code. This is probably best left for the compiler to decide and should be removed.

`assume_aligned` concerns the alignment of incoming data structures from DOLFINX (or other code). At the moment a safe default is that all incoming data structures are assumed unaligned (or, minimally aligned). This means that even if a user uses `-march=native` to JIT compile FFCX generated code, the compiler will not emit AVX instructions acting on the incoming data.

I would propose changing the default of `assume_aligned` to `32` which is consistent with the default alignment of Eigen arrays in DOLFINX. This will allow the compiler to emit more AVX instructions if `-march=native` is turned on.

**Comment by jhale** [comment]
Additionally it was suggested by @michalhabera to manually write the assumed alignment into FFCX generated code as a variable so that client libraries like DOLFINX can check that their memory alignment is sufficient at runtime.

**Comment by garth-wells** [comment]
I don't think there should be a default alignment - it is a recipe for trouble. Just leave it to the user to set via an FFCX option.

**Comment by jhale** [comment]
There is no trouble with having over-aligned memory. We've had 32 in dolfinx for a long time with no issues.

Another option would be for dolfinx to pass it's alignment to ffcx at JIT time?

**Comment by garth-wells** [comment]
We should 'interfere' as little as possible (keep code vanilla) but make full control possible, e.g. in this case via FFCX options. That's been a driving philosophy behind DOLFINX.

**Comment by michalhabera** [comment]
Part of this was solved with #284 . The part for `assume_aligned` is still open.
I would propose to store assumed alignment as a part of `struct ufc_integral`, with default being `-1`, i.e. no assumed alignment invoked inside the kernel.

This could be then easily checked runtime in dolfinx when `dolfinx::Form` is constructed. Or any other 3rd party would know what alignment is assumed, so it can allocate memory accordingly.

**Comment by garth-wells** [comment]
Closing for now. Profiling of recent changes show very good auto vectorisation.
