### ISSUE TITLE
Unable to set quadrature degree

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/ffcx#288]
I have a form file that compiles just fine, except I get a warning saying `UserWarning: Number of integration points per cell is: 216. Consider using 'quadrature_degree' to reduce number.`.
I tried to do just that with `ffcx --quadrature_degree 4 file.ufl` but I get an error saying `ffcx: error: unrecognized arguments: --quadrature_degree`. The usage help doesn't mention any such option either.
What should I do?

**Comment by massimiliano-leoni** [comment]
In the meantime, I found that I can set it in the ufl file creating a new measure
```
dX = dx(metadata={"quadrature_degree": 4})
```

**Comment by michalhabera** [comment]
Yes, that is the correct way. Quad degree, quad scheme and precision were removed from parameters because they are naturally UFL metadata. Handling metadata as parameters was always messy and confusing.

Just run `ffcx --help` to get all available true parameters.
