### ISSUE TITLE
Fuse Tabulate Tensor Loops

### ISSUE THREAD

**Issue by IgorBaratta** [FEniCS/ffcx#305]
It might be beneficial to fuse some loops in the main body of the generated code. Since the same data (local matrix) is referenced in many loops over the same iteration range, combining them can improve the locality of reference. 

A simple example with P2 elements (helmholtz equation), the main body of the generated code currently is:
```c
for (int iq = 0; iq < 15; ++iq)
{
    const ufc_scalar_t fw0 = sp_929[73] * weights_929[iq];
    for (int i = 0; i < 10; ++i)
        for (int j = 0; j < 10; ++j)
            A[10 * i + j] += fw0 * FE17_C0_Q929[0][0][iq][i] * FE17_C0_Q929[0][0][iq][j];
    const ufc_scalar_t fw1 = sp_929[74] * weights_929[iq];
    ....
    ....
    for (int i = 0; i < 10; ++i)
        for (int j = 0; j < 10; ++j)
            A[10 * i + j] += fw5 * FE17_C0_D001_Q929[0][0][iq][i] * FE17_C0_D010_Q929[0][0][iq][j];
    const ufc_scalar_t fw6 = sp_929[79] * weights_929[iq];
    for (int i = 0; i < 10; ++i)
        for (int j = 0; j < 10; ++j)
            A[10 * i + j] += fw6 * FE17_C0_D001_Q929[0][0][iq][i] * FE17_C0_D001_Q929[0][0][iq][j];
}
```
and by fusing the loops:
```c
for (int iq = 0; iq < 15; ++iq)
{
    const ufc_scalar_t fw0 = sp_929[73] * weights_929[iq];
    const ufc_scalar_t fw1 = sp_929[74] * weights_929[iq];
    const ufc_scalar_t fw2 = sp_929[75] * weights_929[iq];
    const ufc_scalar_t fw3 = sp_929[76] * weights_929[iq];
    const ufc_scalar_t fw4 = sp_929[77] * weights_929[iq];
    const ufc_scalar_t fw5 = sp_929[78] * weights_929[iq];
    const ufc_scalar_t fw6 = sp_929[79] * weights_929[iq];
    for (int i = 0; i < 10; ++i)
        for (int j = 0; j < 10; ++j)
        {
            A[10 * i + j] += fw0 * FE17_C0_Q929[0][0][iq][i] * FE17_C0_Q929[0][0][iq][j];
            A[10 * i + j] += fw1 * FE17_C0_D100_Q929[0][0][iq][i] * FE17_C0_D100_Q929[0][0][iq][j];
            A[10 * i + j] += fw2 * FE17_C0_D100_Q929[0][0][iq][i] * FE17_C0_D010_Q929[0][0][iq][j];
            A[10 * i + j] += fw3 * FE17_C0_D100_Q929[0][0][iq][i] * FE17_C0_D001_Q929[0][0][iq][j];
            A[10 * i + j] += fw2 * FE17_C0_D010_Q929[0][0][iq][i] * FE17_C0_D100_Q929[0][0][iq][j];
            A[10 * i + j] += fw4 * FE17_C0_D010_Q929[0][0][iq][i] * FE17_C0_D010_Q929[0][0][iq][j];
            A[10 * i + j] += fw5 * FE17_C0_D010_Q929[0][0][iq][i] * FE17_C0_D001_Q929[0][0][iq][j];
            A[10 * i + j] += fw3 * FE17_C0_D001_Q929[0][0][iq][i] * FE17_C0_D100_Q929[0][0][iq][j];
            A[10 * i + j] += fw5 * FE17_C0_D001_Q929[0][0][iq][i] * FE17_C0_D010_Q929[0][0][iq][j];
            A[10 * i + j] += fw6 * FE17_C0_D001_Q929[0][0][iq][i] * FE17_C0_D001_Q929[0][0][iq][j];
        }
}
```

I ran some numerical experiments (matrix assembly), and the speedup ranged from 1.5x (using PETSc) to 4x (custom assembler) with different compilers (Intel, gcc, clang). In GPUS using a custom assembler the speedup reached up to 5x.

**Comment by michalhabera** [comment]
Loop fusion should be done by a C compiler. Can you specify more what flags you used? Why was speedup different depending on data structure to which you assembled?

**Comment by IgorBaratta** [comment]
> Loop fusion should be done by a C compiler.

It could potentially be done by a C compiler, but it doesn't always happen.
OTOH, the second loop is less complicated and more prone to optimizations like loop fission.

clang opt viewer can reveal some missed optimizations in the original code compared to the fused one:
https://godbolt.org/z/zETfdd

> Can you specify more what flags you used?
I used several compiler/flag combinations, including the standard `-march=native -O3`.. `O2` `Ofast`.

> Why was speedup different depending on data structure to which you assembled?
Besides calling the generated code PETSc performs other operations (such as search, column insertion, communication, etc...)  The custom assembler I'm referring to basically assembles local matrices and stack them.

**Comment by IgorBaratta** [comment]
A simple benchmark can be found at:
https://quick-bench.com/q/uspouXjZ-GNWo9FvB7jX6o6vmM4
