### ISSUE TITLE
Are the extra permutation tables necessary for exterior facet integrals?

### ISSUE THREAD

**Issue by jpdean** [FEniCS/ffcx#426]
The generated code for exterior facet integrals contains tables with basis functions tabulated for each permutation, for instance:

```
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE3_C0_F_Q4a8[2][3][2][3] =
        { { { { 0.0, 0.7886751345948129, 0.2113248654051871 },
              { 0.0, 0.2113248654051871, 0.7886751345948129 } },
            { { 0.7886751345948129, 0.0, 0.2113248654051871 },
              { 0.2113248654051871, 0.0, 0.7886751345948129 } },
            { { 0.7886751345948129, 0.2113248654051871, 0.0 },
              { 0.2113248654051873, 0.7886751345948129, 0.0 } } },
          { { { 0.0, 0.2113248654051871, 0.7886751345948129 },
              { 0.0, 0.7886751345948129, 0.2113248654051871 } },
            { { 0.2113248654051871, 0.0, 0.7886751345948129 },
              { 0.7886751345948129, 0.0, 0.2113248654051871 } },
            { { 0.2113248654051873, 0.7886751345948129, 0.0 },
              { 0.7886751345948129, 0.2113248654051871, 0.0 } } } };
```
However, since exterior facet integral kernels take only one permutation value, i.e. only `quadrature_permutation[0]` is ever used, it seems to me that the kernel will always compute the same values regardless of the value of the permutation. If this is the case, can the extra tables be removed to simplify the code?

**Comment by mscroggs** [comment]
All the DOLFINx tests pass if we just pass 0 into exterior facet kernels instead of the actual facet permutation, so I'm confident that this permuting isn't needed. I'll get working on a PR
