### ISSUE TITLE
`PyGraphviz requires Python version 3.8 or later (3.7 detected).`

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/ffcx#449]
I'm getting this error when running CI (https://github.com/FEniCS/ffcx/runs/5035402568?check_suite_focus=true). Do we need to bump our minimum Python requirement to 3.8?

**Comment by jorgensd** [comment]
According to pypi it should work with 3.7: https://pypi.org/project/pygraphviz/1.8/.

**Comment by jorgensd** [comment]
Or maybe the meta-data is wrong.
as `Programming language` does not include python 3.7.
I guess we could fix pygraphviz to one lower version: (https://pypi.org/project/pygraphviz/1.7/) as it supports python3.7

**Comment by mscroggs** [comment]
Looks like the metadata is wrong, as it checkes if the version is below 3.8 at https://github.com/pygraphviz/pygraphviz/blob/9ec45f388df15252791dc15f6f699bf0b257be7a/setup.py#L6
