### ISSUE TITLE
still supporting python 3.7, or not?

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/ffcx#516]
Hi,
#511 has broken python 3.7 compatibility, with the following error
```
  File "/usr/local/lib/python3.7/site-packages/ffcx/element_interface.py", line 28, in <module>
    @lru_cache
  File "/usr/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
```

For my [FEM on Colab](https://fem-on-colab.github.io/) project I still need to support such an old version of python. I can easily patch this error (`lru_cache` to `lru_cache()`), but I thought this might be a good occasion to raise this issue asking if you are still supporting py3.7 or not. CI seems to suggest not, but such version is still listed in `python_requires = >= 3.7` in `setup.cfg`.

Cheers,
Francesco

**Comment by garth-wells** [comment]
@mscroggs?

**Comment by mscroggs** [comment]
I've forgotten why we turned 3.7 off in the CI. I'll attempt to get it turned back on so we know we're supporting 3.7 and catch future mistakes like this

**Comment by francesco-ballarin** [comment]
> In DOLFINx we only support python >=3.8. I think it has to do with typing

If I remember correctly it had to do with numpy typing. Still, (upon patching the check in setup.py) simple dolfinx notebooks run correctly even with python 3.7. I cannot vouch for the whole testuite, since I do not run that.

**Comment by garth-wells** [comment]
We dropped Python 3.7 from the FFCx CI because pygraphviz is Python >=3.8. FFCx uses pygraphviz to visualise ASTs, but not for anything ‘core’.
