### ISSUE TITLE
Vector element matrices

### ISSUE THREAD

**Issue by jakob0** [FEniCS/ffcx#546]
Hello.
I've been playing around with vector elements (Nedelec...) and have a question.
When I generate a function with ffcx for an element of at least second order, the basis function matrix has different values than the one generated by basix with the tabulate option.
Are you using another basis in ffcx than in basix, or are the values somehow modified afterwards for vector elements?
Thank you
Jakob

**Comment by jorgensd** [comment]
This is a fairly generic question, and I would suggest that you provide an example of:
1. How you generate the data with `basix.tabulate`
2. Create a problem which can compile the forms required to get the matrices in question with ffcx

Show the output of both

**Comment by jakob0** [comment]
Sorry.
I generate the basix values like this:
`import basix
import numpy

numpy.set_printoptions(linewidth=numpy.inf)

element = basix.create_element(
    basix.ElementFamily.N1E, basix.CellType.triangle, 2)

quadrature, weights = basix.make_quadrature(
    basix.QuadratureType.gauss_jacobi, basix.CellType.triangle, 3)


print('Points:')
print(quadrature)
print(weights)


print()
print('Matrices:')
ff = element.tabulate(0, quadrature);

x = ff[0,:, :, 0]
y = ff[0,:, :, 1]

print(x)
print()
print(y)
`

and in ffcx I use the ufl file like this:
`from ufl import (FiniteElement, action, inner, TestFunction, TrialFunction, dx, triangle)
element  = FiniteElement("N1curl",triangle, 2)
u = TrialFunction(element)
v = TestFunction (element)
a = action(inner(v,u)*dx(metadata={"quadrature_degree": 3}, scheme="gauss_jacobi"))
`
The output of basix is:
`[[ 0.08861634  0.42787754  0.51649388 -0.42787754  1.4818476  -0.84003129  1.87467757 -0.60511022]
 [ 0.90276805 -0.74787754  0.15489051  0.74787754 -0.47477102 -0.64704529  3.27670682 -1.05765856]
 [-0.51649388  0.42787754 -0.08861634 -0.42787754 -0.84003129  1.4818476   1.26956735  0.60511022]
 [-0.15489051 -0.74787754 -0.90276805  0.74787754 -0.64704529 -0.47477102  2.21904826  1.05765856]]

[[-0.45916916 -0.13563174  1.40354057 -0.9340621   0.5948009  -0.45916916 -0.73043265  2.12532243]
 [-0.2550871   0.23706768 -0.33789993  1.63262617  0.01801942 -0.2550871   0.21904826  0.72329318]
 [ 0.8870467  -0.50618456 -0.5477855  -0.56350928 -0.38086213  0.8870467  -0.12532243  2.73043265]
 [-0.49279044  0.88474863 -1.15785515  0.98494522 -0.39195819 -0.49279044  1.27670682  1.78095174]]
`
And the output from ffcx is:
`
  static const double FE8_C0_Qe9b[1][1][4][8] =
    { { { { 0.2582469389803321, 0.09793627216151329, 0.0443081698463488, -0.2726165456872939, 0.3209081537009703, -0.6702687007525373, 1.325597222680396, -0.4278775382679597 },
          { 0.07744525483619691, -0.4765003367670169, 0.4513840239701751, 0.1711806102928021, -0.5609081537009751, -0.04973129924746761, 2.316981610313457, -0.7478775382679541 },
          { -0.04430816984635007, 0.2726165456872905, -0.2582469389803296, -0.09793627216151043, 0.3209081537009739, 0.6702687007525382, 0.8977196844124292, 0.4278775382679582 },
          { -0.4513840239701797, -0.171180610292807, -0.0774452548361951, 0.476500336767023, -0.5609081537009687, 0.0497312992474665, 1.569104072045488, 0.7478775382679579 } } } };
  static const double FE8_C1_Qe9b[1][1][4][8] =
    { { { { -0.2974004511590375, 0.09339720617637809, 0.2347392364383955, -0.6748077667376732, 0.06781587238828249, -0.3042549488888689, -0.5164938779606604, 1.5028299020658 },
          { -0.00900971035473816, 0.1420728476615487, 0.6473631188919087, 0.5688418851811078, -0.1185338400855287, -0.07883906187871736, 0.1548905096723941, 0.5114455144327352 },
          { 0.190431066592048, -0.4021912210503782, -0.5556473901393701, -0.004539065985136649, 0.2530922813126862, 0.366013751863669, -0.088616339692699, 1.930707440333758 },
          { 0.1959790949217274, 0.3976612748882991, -0.08645496519093258, 0.6185731844285742, -0.4423743136154376, -0.02910776263125158, 0.9027680479403519, 1.259323052700695 } } } };
`

Thanks for your help.

**Comment by IgorBaratta** [comment]
Hi @jakob0 ,

ffcx uses `basix.LagrangeVariant.legendre` as the default lagrange variant for P>1.

If you add that option to your original python script, you will get similar results for your script and ffcx. 
```python
element = basix.create_element(
    basix.ElementFamily.N1E, basix.CellType.triangle, 2, 
    basix.LagrangeVariant.legendre)
```
Hope it helps.

**Comment by jakob0** [comment]
Ahhh, thanks a lot!
I thought the LagrangeVariant option was only available for Lagrange elements.
Does this mean, that all dofs of subspaces, like tangent integral moments will be created with Legendre points?
I was trying to get the basis function for different variants in symfem, but they all look the same...

Anyway, that was really helpfull, thanks!
