### ISSUE TITLE
Remove unused or experimental options

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/ffcx#598]
Remove unused options: `tabulate_tensor_void`, `padlen`, `assume_aligned`.

**Comment by michalhabera** [comment]
`tabulate_tensor_void` is an option to benchmark the cost of dolfinx assembly loop.

**Comment by michalhabera** [comment]
Not really. Also, arguably, benchmarking dolfinx assembly loop is only for advanced users if ever needed, and they could pass void kernels themselves.
