### ISSUE TITLE
Include 'prefix' (filename) in function hash when using FFC from the command line

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/ffcx#6]
When using FFC from the command line (rather than JIT), the file name, e.g. `Poisson` was included in the class names. Now that the command line and JIT follow a common code path and use hashes in in the classes name we need to add the filename to the hash when using FFC from the command line to avoid name clashes across more than one generated file.

**Comment by chrisrichardson** [comment]
Now fixed
