### ISSUE TITLE
warning: implicit declaration of function ‘real’; did you mean ‘creal’?

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/ffcx#602]
Generated code for a form is giving this warning. See eg https://github.com/FEniCS/basix/actions/runs/6094169143/job/16535151559?pr=682

**Comment by chrisrichardson** [comment]
Is this because `ufl` is asking for the `real` part or `conj` of a real number (non complex)? Does it ever ask for `imag(x)` - I guess that should return zero, in this case...

**Comment by mscroggs** [comment]
Yes, I believe that's the issue. It was asking for the real part of one of the coordinates (which is a double)
