### ISSUE TITLE
Move uflacs/analysis/balancing.py to UFL

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/ffcx#63]
The function `balance_modifiers()` in uflacs is just UFL code. 
As suggested in a comment, it would be better to move out of FFC.

**Comment by garth-wells** [comment]
See https://bitbucket.org/fenics-project/ufl/pull-requests/104/move-balancing-over-from-ffc/.

**Comment by garth-wells** [comment]
See https://github.com/FEniCS/ffcx/pull/89.
