### ISSUE TITLE
Generate code for cell geometry data

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/ffcx#65]
See https://bitbucket.org/fenics-project/ffc/issues/169/replace-tables-from-ufc_geometryh-by.

This would help the generation of dofmap for higher-order bases, and ensure consistency with FIAT and generated code.

**Comment by mscroggs** [comment]
Assigning this to me as it's on my to do list once the Basix PR is merged

**Comment by garth-wells** [comment]
See https://github.com/FEniCS/basix/pull/222.
