### ISSUE TITLE
CI requires `numba` but does not test it.

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/ffcx#660]
In `pyproject.toml`, `ci` includes the `optional` dependencies of `pygraphviz` and `numba`, but `numba` doesn't appear in any tests.

Do we want to add a `numba` test?

Currently `numba` is preventing testing with Python 3.12, but it will get support soon.

**Comment by jorgensd** [comment]
It would be good to have a test that checks: 
https://github.com/FEniCS/ffcx/blob/2911b25f4bcc3e3bf00c3382c2a5a05112e1de06/ffcx/codegeneration/utils.py#L60
